services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    # ports:
    #   - '8080:5502'
    command: npm start
    env_file:
      - .env
